DEVICE     = atmega328p
CLOCK      = 16000000
OBJECTS    = src/main.o src/spi.o src/mcp2515.o
# clockout at PORTB0
FUSES      = -U lfuse:w:0xbe:m -U hfuse:w:0xd9:m -U efuse:w:0x07:m
# generated by http://www.engbedded.com/fusecalc/

AVRDUDE = avrdude -p$(DEVICE)
COMPILE = avr-gcc -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

all:	main.hex avr-size

%.o:	%.c
	$(COMPILE) -c $< -o $@

flash-arduino:	all
	sudo python /home/marenz/programming/avr/arduino_scripts/arduino_reset.py /dev/ttyUSB0
	sudo $(AVRDUDE) -C/usr/share/arduino/hardware/tools/avrdude.conf -q -q -cstk500v1 -P/dev/ttyUSB0 -b57600 -D -U flash:w:main.hex

flash-usbasp:	all
		sudo $(AVRDUDE) -cusbasp -U flash:w:main.hex

fuse:
	sudo $(AVRDUDE) -cusbasp $(FUSES)

install: flash fuse

clean:
	rm -f main.hex main.elf $(OBJECTS)

main.elf: $(PLATFORM_OBJECTS) $(OBJECTS)
	$(COMPILE) -o main.elf $(OBJECTS)

main.hex: main.elf
	rm -f main.hex
	avr-objcopy -j .text -j .data -O ihex main.elf main.hex

disasm:	main.elf
	avr-objdump -D main.elf

avr-size: main.elf
	avr-size main.elf --mcu=$(DEVICE) --format=avr

docs:
	doxygen DOXYFILE
